-- Create the 'brands' table
CREATE TABLE brands (
    id INT PRIMARY KEY AUTO_INCREMENT,
    brand_name VARCHAR(255) NOT NULL
);

-- Create the 'models' table
CREATE TABLE models (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    average_price INT NOT NULL,
    brand_id INT NOT NULL,
    FOREIGN KEY (brand_id) REFERENCES brands(id)
);

-- Insert data into the 'brands' table
INSERT INTO brands (brand_name) VALUES ('Abarth');
INSERT INTO brands (brand_name) VALUES ('Acura');
INSERT INTO brands (brand_name) VALUES ('Alfa Romeo');
INSERT INTO brands (brand_name) VALUES ('Aston Martin');
INSERT INTO brands (brand_name) VALUES ('Audi');
INSERT INTO brands (brand_name) VALUES ('BMW');
INSERT INTO brands (brand_name) VALUES ('Baic');
INSERT INTO brands (brand_name) VALUES ('Bentley');
INSERT INTO brands (brand_name) VALUES ('Buick');
INSERT INTO brands (brand_name) VALUES ('Cadillac');
INSERT INTO brands (brand_name) VALUES ('Cbo');
INSERT INTO brands (brand_name) VALUES ('Chevrolet');
INSERT INTO brands (brand_name) VALUES ('Chrysler');
INSERT INTO brands (brand_name) VALUES ('Dodge');
INSERT INTO brands (brand_name) VALUES ('FAW');
INSERT INTO brands (brand_name) VALUES ('Ferrari');
INSERT INTO brands (brand_name) VALUES ('Fiat');
INSERT INTO brands (brand_name) VALUES ('Ford');
INSERT INTO brands (brand_name) VALUES ('GMC');
INSERT INTO brands (brand_name) VALUES ('HINO');
INSERT INTO brands (brand_name) VALUES ('Honda');
INSERT INTO brands (brand_name) VALUES ('Hummer');
INSERT INTO brands (brand_name) VALUES ('Hyundai');
INSERT INTO brands (brand_name) VALUES ('Infiniti');
INSERT INTO brands (brand_name) VALUES ('International');
INSERT INTO brands (brand_name) VALUES ('Isuzu');
INSERT INTO brands (brand_name) VALUES ('JAC');
INSERT INTO brands (brand_name) VALUES ('Jaguar');
INSERT INTO brands (brand_name) VALUES ('Jeep');
INSERT INTO brands (brand_name) VALUES ('KIA');
INSERT INTO brands (brand_name) VALUES ('Lamborghini');
INSERT INTO brands (brand_name) VALUES ('Land Rover');
INSERT INTO brands (brand_name) VALUES ('Lincoln');
INSERT INTO brands (brand_name) VALUES ('Lotus');
INSERT INTO brands (brand_name) VALUES ('MG');
INSERT INTO brands (brand_name) VALUES ('Maserati');
INSERT INTO brands (brand_name) VALUES ('Mastretta');
INSERT INTO brands (brand_name) VALUES ('Mazda');
INSERT INTO brands (brand_name) VALUES ('McLaren');
INSERT INTO brands (brand_name) VALUES ('Mercedes Benz');
INSERT INTO brands (brand_name) VALUES ('Mercury');
INSERT INTO brands (brand_name) VALUES ('Mini Cooper');
INSERT INTO brands (brand_name) VALUES ('Mitsubishi');
INSERT INTO brands (brand_name) VALUES ('Nissan');
INSERT INTO brands (brand_name) VALUES ('Peugeot');
INSERT INTO brands (brand_name) VALUES ('Pontiac');
INSERT INTO brands (brand_name) VALUES ('Porsche');
INSERT INTO brands (brand_name) VALUES ('RAM');
INSERT INTO brands (brand_name) VALUES ('Renault');
INSERT INTO brands (brand_name) VALUES ('Rolls Royce');
INSERT INTO brands (brand_name) VALUES ('Saab');
INSERT INTO brands (brand_name) VALUES ('Seat');
INSERT INTO brands (brand_name) VALUES ('Smart');
INSERT INTO brands (brand_name) VALUES ('Subaru');
INSERT INTO brands (brand_name) VALUES ('Suzuki');
INSERT INTO brands (brand_name) VALUES ('Tesla');
INSERT INTO brands (brand_name) VALUES ('Toyota');
INSERT INTO brands (brand_name) VALUES ('UAZ');
INSERT INTO brands (brand_name) VALUES ('Volkswagen');
INSERT INTO brands (brand_name) VALUES ('Volvo');
INSERT INTO brands (brand_name) VALUES ('Zacua');

INSERT INTO models (id, name, average_price, brand_id) VALUES (1, 'ILX', 303176, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (2, 'MDX', 448193, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (3, 'RDX', 395753, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (4, 'RLX', 453100, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (5, 'TL', 247225, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (6, 'TSX', 232533, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (7, 'A1', 260696, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (9, 'A3', 255299, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (10, 'A4', 299412, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (11, 'A5', 511069, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (12, 'A6', 499782, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (13, 'A7', 1040891, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (14, 'A8', 1059155, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (15, 'Q3', 454949, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (16, 'Q5', 532993, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (17, 'Q7', 593487, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (18, 'R8', 1463936, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (21, 'TT', 498670, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (24, 'Continental', 0, (SELECT id FROM brands WHERE brand_name = 'Bentley'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (25, 'Flying Spur', 3968000, (SELECT id FROM brands WHERE brand_name = 'Bentley'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (26, 'Continental GT', 4498875, (SELECT id FROM brands WHERE brand_name = 'Bentley'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (27, 'Mulsanne', 3968000, (SELECT id FROM brands WHERE brand_name = 'Bentley'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (54, 'X6', 898716, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (60, 'Enclave', 583200, (SELECT id FROM brands WHERE brand_name = 'Buick'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (61, 'Encore', 335845, (SELECT id FROM brands WHERE brand_name = 'Buick'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (62, 'LaCrosse', 419233, (SELECT id FROM brands WHERE brand_name = 'Buick'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (63, 'Regal', 352460, (SELECT id FROM brands WHERE brand_name = 'Buick'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (64, 'Verano', 325409, (SELECT id FROM brands WHERE brand_name = 'Buick'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (65, 'ATS', 737342, (SELECT id FROM brands WHERE brand_name = 'Cadillac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (66, 'CTS', 636500, (SELECT id FROM brands WHERE brand_name = 'Cadillac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (70, 'SRX', 422207, (SELECT id FROM brands WHERE brand_name = 'Cadillac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (71, 'Aveo', 128557, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (72, 'Camaro', 507271, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (74, 'Cheyenne', 345435, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (75, 'Colorado', 284984, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (76, 'Cruze', 227283, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (80, 'Malibu', 238000, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (81, 'Matiz', 56821, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (84, 'Sonic', 146029, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (85, 'Spark', 144415, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (86, 'Suburban', 572851, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (87, 'Tahoe', 519019, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (88, 'Tornado', 152882, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (89, 'Traverse', 412188, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (90, 'Trax', 236175, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (91, 'Chrysler 200', 283907, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (92, 'Chrysler 300', 366584, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (93, 'Town', 317192, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (94, 'Attitude', 121966, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (95, 'Avenger', 134104, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (96, 'Challenger', 630386, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (97, 'Charger', 376721, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (98, 'Dart', 278366, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (99, 'Durango', 294664, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (101, 'Journey', 274681, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (102, 'GF250 ', 0, (SELECT id FROM brands WHERE brand_name = 'FAW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (103, 'GF6000', 0, (SELECT id FROM brands WHERE brand_name = 'FAW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (104, 'GF70', 112600, (SELECT id FROM brands WHERE brand_name = 'FAW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (105, 'GF7000', 0, (SELECT id FROM brands WHERE brand_name = 'FAW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (106, 'GF8', 103500, (SELECT id FROM brands WHERE brand_name = 'FAW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (107, 'GF900', 0, (SELECT id FROM brands WHERE brand_name = 'FAW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (110, 'California', 0, (SELECT id FROM brands WHERE brand_name = 'Ferrari'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (112, 'FF', 0, (SELECT id FROM brands WHERE brand_name = 'Ferrari'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (113, 'Ducato', 0, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (114, 'F500', 0, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (115, 'Palio', 130515, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (116, 'Palio Adventure', 0, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (117, 'Punto', 181600, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (118, 'Palio Strada', 110558, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (119, 'Strada Adventure', 0, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (120, 'Uno', 161305, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (121, 'E-150', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (122, 'E-350', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (123, 'Eco Sport', 189465, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (124, 'Edge', 408952, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (125, 'Escape', 226759, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (126, 'Expedition', 436655, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (127, 'Explorer', 318270, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (128, 'F-150', 268727, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (129, 'F-250', 201785, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (130, 'F-350', 287341, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (131, 'F-450', 320575, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (132, 'F-550', 370436, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (133, 'Fiesta', 138747, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (134, 'Focus', 189192, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (135, 'Fusion', 252518, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (136, 'Ikon hatchback', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (137, 'Lobo', 363385, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (138, 'Lobo Raptor', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (139, 'Mustang', 367921, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (140, 'Ranger', 210497, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (141, 'Transit', 278628, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (142, 'Acadia', 400347, (SELECT id FROM brands WHERE brand_name = 'GMC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (143, 'Sierra', 464248, (SELECT id FROM brands WHERE brand_name = 'GMC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (146, 'Terrain', 444504, (SELECT id FROM brands WHERE brand_name = 'GMC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (147, 'Yukon', 556491, (SELECT id FROM brands WHERE brand_name = 'GMC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (148, 'Accord', 221035, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (149, 'City', 166870, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (150, 'Civic', 185562, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (151, 'CR-V', 247293, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (152, 'CR-Z', 209033, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (153, 'Crosstour', 255420, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (154, 'Fit', 142098, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (155, 'Odyssey', 343033, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (156, 'Pilot', 331339, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (157, 'Ridge Line', 253687, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (158, 'Q60', 673900, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (159, 'Q70', 651500, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (160, 'QX60', 665011, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (161, 'QX70', 660861, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (162, 'QX80', 951850, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (163, 'F', 1484528, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (164, 'XF', 791032, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (165, 'XJ', 606150, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (166, 'XKR', 0, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (167, 'Cherokee', 456109, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (168, 'Compass', 263629, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (169, 'Grand Cherokee', 562944, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (170, 'Patriot', 185558, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (171, 'Wrangler', 396757, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (173, 'Aventador', 0, (SELECT id FROM brands WHERE brand_name = 'Lamborghini'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (174, 'Gallardo', 0, (SELECT id FROM brands WHERE brand_name = 'Lamborghini'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (175, 'Defender', 923797, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (176, 'Discovery', 1019830, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (177, 'LR2', 482077, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (178, 'Range Rover', 1762459, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (179, 'Mark LT', 318420, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (180, 'MKS', 309425, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (181, 'MKX', 429064, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (182, 'MKZ', 417642, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (183, 'Navigator', 578993, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (184, 'Gran Cabrio', 0, (SELECT id FROM brands WHERE brand_name = 'Maserati'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (185, 'Gran Turismo', 2810925, (SELECT id FROM brands WHERE brand_name = 'Maserati'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (186, 'Quattroporte', 2263000, (SELECT id FROM brands WHERE brand_name = 'Maserati'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (187, 'MXT', 0, (SELECT id FROM brands WHERE brand_name = 'Mastretta'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (188, 'Mazda 2', 183824, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (189, 'Mazda 3', 192010, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (191, 'Mazda 5', 135327, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (192, 'Mazda 6', 194683, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (194, 'CX9', 383370, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (195, 'MX5', 261504, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (196, 'Clase A', 463191, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (197, 'Clase B', 239151, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (198, 'Clase C', 672744, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (199, 'Clase CLA', 488793, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (200, 'Clase CLS', 767931, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (201, 'Clase E', 727529, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (202, 'Clase G', 2193198, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (203, 'Clase GL', 696475, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (204, 'Clase GLK', 351929, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (205, 'Clase ML', 0, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (206, 'Clase S', 2556844, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (207, 'Clase SL', 1584684, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (208, 'Clase SLK', 530838, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (209, 'Clase SLS AMG', 0, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (210, 'Viano', 433878, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (220, 'ASX', 209442, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (221, 'L200', 215532, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (222, 'Lancer', 153796, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (223, 'Montero', 350767, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (224, 'Outlander', 236435, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (225, '370Z', 440869, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (226, 'Altima', 184092, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (227, 'Armada', 340681, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (228, 'Frontier LE', 0, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (229, 'Frontier XE', 0, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (230, 'Juke', 226880, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (231, 'March', 130214, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (232, 'Maxima', 295525, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (233, 'Murano', 262091, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (234, 'Note', 184206, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (235, 'NP300', 0, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (236, 'Pathfinder', 342334, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (237, 'Rogue', 175936, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (238, 'Sentra', 157613, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (239, 'Titan', 251044, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (240, 'Tsuru', 78120, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (241, 'Urvan', 239288, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (242, 'Versa', 159324, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (243, 'X Trail', 260731, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (245, '207 CC', 0, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (246, '208', 201530, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (249, '3008', 336527, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (250, '301', 184431, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (251, '308', 245043, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (252, '308 CC', 0, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (253, '508', 314191, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (254, 'Manager', 342506, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (257, 'RCZ', 404630, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (258, '911', 1371633, (SELECT id FROM brands WHERE brand_name = 'Porsche'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (267, 'Boxster', 745149, (SELECT id FROM brands WHERE brand_name = 'Porsche'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (269, 'Cayenne', 941314, (SELECT id FROM brands WHERE brand_name = 'Porsche'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (270, 'Cayman', 743222, (SELECT id FROM brands WHERE brand_name = 'Porsche'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (272, 'Panamera', 1500840, (SELECT id FROM brands WHERE brand_name = 'Porsche'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (278, 'Bighorn', 0, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (279, 'Crew Cab', 0, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (281, 'Hemi Sport', 0, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (282, 'Power Wagon', 0, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (283, 'Regular Cab R/T', 0, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (284, 'Regular Cab SLT', 0, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (285, 'ST', 0, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (286, 'Duster', 209145, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (287, 'Fluence', 169802, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (288, 'Kangoo', 60585, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (289, 'Koleos', 257672, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (290, 'Safrane', 181925, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (291, 'Sandero', 126814, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (292, 'Stepway', 167890, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (294, 'Ghost', 0, (SELECT id FROM brands WHERE brand_name = 'Rolls Royce'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (295, 'Phantom', 0, (SELECT id FROM brands WHERE brand_name = 'Rolls Royce'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (296, 'Altea', 141055, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (297, 'Freetrack', 164408, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (298, 'Ibiza', 156859, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (299, 'Leon', 234543, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (301, 'Toledo', 191512, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (302, 'Brabus', 0, (SELECT id FROM brands WHERE brand_name = 'Smart'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (303, 'Fortwo', 0, (SELECT id FROM brands WHERE brand_name = 'Smart'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (304, 'Forester', 307996, (SELECT id FROM brands WHERE brand_name = 'Subaru'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (305, 'Impreza', 232322, (SELECT id FROM brands WHERE brand_name = 'Subaru'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (306, 'Legacy', 231704, (SELECT id FROM brands WHERE brand_name = 'Subaru'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (307, 'Outback', 294950, (SELECT id FROM brands WHERE brand_name = 'Subaru'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (308, 'WRX', 344748, (SELECT id FROM brands WHERE brand_name = 'Subaru'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (309, 'XV', 310570, (SELECT id FROM brands WHERE brand_name = 'Subaru'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (310, 'Grand Vitara', 197100, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (311, 'Kizashi', 241536, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (312, 'S-Cross', 235612, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (313, 'Swift', 171901, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (314, 'SX 4 Crossover', 0, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (316, 'SX 4 Sedan ', 0, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (317, 'Avanza', 161502, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (318, 'Camry', 260490, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (319, 'Corolla', 180456, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (320, 'FJ Cruiser', 301680, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (321, 'Hiace', 226078, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (322, 'Highlander', 375704, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (323, 'Hilux', 209308, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (324, 'Land Cruiser', 700584, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (325, 'Prius', 281072, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (326, 'Rav4', 254634, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (327, 'Sequoia', 490790, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (328, 'Sienna', 329930, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (329, 'Tacoma', 352954, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (330, 'Tundra', 402731, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (333, 'Amarok', 341421, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (334, 'Beetle', 174920, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (335, 'CC', 299380, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (336, 'Clasico', 0, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (337, 'CrossFox', 158882, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (338, 'Gol', 115926, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (339, 'Gol Sedan', 0, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (340, 'Jetta Clasico', 100096, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (341, 'Passat', 216005, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (342, 'Polo', 165026, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (343, 'Saveiro', 199246, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (344, 'Tiguan', 317202, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (345, 'Touareg', 483431, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (346, 'Vento', 175146, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (347, 'S60', 372106, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (348, 'S80', 256982, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (349, 'V40', 332068, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (351, 'V60', 460872, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (352, 'XC60', 498311, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (353, 'XC90', 587919, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (354, 'RL', 239050, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (355, 'ZDX', 405550, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (356, '147', 0, (SELECT id FROM brands WHERE brand_name = 'Alfa Romeo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (357, '166', 0, (SELECT id FROM brands WHERE brand_name = 'Alfa Romeo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (358, '4C', 1081850, (SELECT id FROM brands WHERE brand_name = 'Alfa Romeo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (359, 'Giulietta', 457240, (SELECT id FROM brands WHERE brand_name = 'Alfa Romeo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (360, 'MiTo', 345862, (SELECT id FROM brands WHERE brand_name = 'Alfa Romeo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (366, 'i3', 671180, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (367, 'i8', 2195133, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (373, 'Serie 1', 277295, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (374, 'Serie 2', 584746, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (375, 'Serie 3', 415477, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (376, 'Serie 4', 758820, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (377, 'Serie 5', 553739, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (378, 'Serie 6', 891559, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (379, 'Serie 7', 1132673, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (380, 'Serie 8', 2179900, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (381, 'X1', 373718, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (382, 'X3', 398124, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (383, 'X4', 730075, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (384, 'X5', 796909, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (386, 'Z', 479845, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (387, 'LeSabre', 0, (SELECT id FROM brands WHERE brand_name = 'Buick'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (388, 'Rendezvous', 0, (SELECT id FROM brands WHERE brand_name = 'Buick'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (389, 'Terraza', 0, (SELECT id FROM brands WHERE brand_name = 'Buick'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (391, 'BLS', 113350, (SELECT id FROM brands WHERE brand_name = 'Cadillac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (392, 'DTS', 0, (SELECT id FROM brands WHERE brand_name = 'Cadillac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (394, 'STS', 192210, (SELECT id FROM brands WHERE brand_name = 'Cadillac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (395, '3500', 253193, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (397, 'Astra', 79910, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (398, 'Avalanche', 289500, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (399, 'Blazer', 697900, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (403, 'Captiva', 204955, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (408, 'Chevy', 61489, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (410, 'Cobalt', 0, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (411, 'Corsa', 61780, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (412, 'Corvette', 811984, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (415, 'Epica', 93033, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (416, 'Equinox', 340491, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (417, 'Express', 0, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (418, 'HHR', 94141, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (419, 'Impala', 0, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (420, 'Meriva', 62754, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (422, 'Optra', 78281, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (423, 'S10', 306100, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (424, 'SS R', 0, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (426, 'Sonora', 104450, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (427, 'Tracker', 91066, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (428, 'Trailblazer', 101966, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (429, 'Uplander', 113130, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (431, 'Vectra', 90933, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (432, 'Venture', 0, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (433, 'Zafira', 90400, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (434, 'Aspen', 174762, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (435, 'Avenger', 135956, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (436, 'Cirrus', 126755, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (438, 'Crossfire', 149550, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (439, 'Dart', 220718, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (441, 'Grand Voyager', 0, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (443, 'PT Cruiser', 83738, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (444, 'Pacifica', 521537, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (445, 'Sebring', 0, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (448, 'Voyager', 113932, (SELECT id FROM brands WHERE brand_name = 'Chrysler'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (449, 'Atos', 61385, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (450, 'Caliber', 113914, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (453, 'Dakota', 143623, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (454, 'Grand Caravan', 497464, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (455, 'H 100', 173933, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (456, 'i10', 85793, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (457, 'Intrepid', 0, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (458, 'Magnum', 0, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (460, 'Neon', 254521, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (461, 'Nitro', 157452, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (462, 'RAM', 0, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (468, 'Stratus', 60283, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (469, 'Van 1000', 97850, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (470, 'Verna', 50766, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (471, 'Viper', 890387, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (475, '430', 0, (SELECT id FROM brands WHERE brand_name = 'Ferrari'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (476, '458', 0, (SELECT id FROM brands WHERE brand_name = 'Ferrari'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (477, '599', 0, (SELECT id FROM brands WHERE brand_name = 'Ferrari'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (478, '612', 0, (SELECT id FROM brands WHERE brand_name = 'Ferrari'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (479, 'F12', 0, (SELECT id FROM brands WHERE brand_name = 'Ferrari'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (480, 'La Ferrari', 0, (SELECT id FROM brands WHERE brand_name = 'Ferrari'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (481, '500', 221640, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (482, 'Albea', 75400, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (483, 'Bravo', 117000, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (484, 'Grande Punto', 76657, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (485, 'Linea', 118000, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (486, 'Panda', 77908, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (487, 'Stilo', 97800, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (488, 'Bronco', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (489, 'Club Wagon', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (493, 'Econoline', 171225, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (494, 'Escort', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (495, 'Excursion', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (496, 'F-100', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (499, 'Five Hundred', 82700, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (500, 'Freestar', 100350, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (502, 'Ikon', 98350, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (503, 'Interceptor', 338475, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (504, 'Ka', 45233, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (506, 'Mondeo', 69310, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (508, 'Taurus', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (510, 'Windstar', 0, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (511, 'Canyon', 182000, (SELECT id FROM brands WHERE brand_name = 'GMC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (515, 'Savana', 0, (SELECT id FROM brands WHERE brand_name = 'GMC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (517, 'Element', 0, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (518, 'Passport', 0, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (519, 'H1', 0, (SELECT id FROM brands WHERE brand_name = 'Hummer'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (520, 'H2', 0, (SELECT id FROM brands WHERE brand_name = 'Hummer'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (521, 'H3', 0, (SELECT id FROM brands WHERE brand_name = 'Hummer'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (522, 'Atos', 0, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (523, 'Attitude', 0, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (524, 'Elantra', 224769, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (525, 'Grand i10', 136722, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (527, 'H100', 0, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (528, 'ix35', 200520, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (529, 'Sonata', 300443, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (530, 'Verna', 0, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (531, 'FX', 500350, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (532, 'FX 50', 0, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (533, 'G', 357625, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (534, 'I30', 0, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (535, 'JX', 430200, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (536, 'Q 45', 0, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (537, 'Q50', 519076, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (538, 'QX', 0, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (539, 'Rodeo', 0, (SELECT id FROM brands WHERE brand_name = 'Isuzu'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (540, 'S-Type', 150450, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (541, 'X-Type', 122725, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (542, 'XK', 615857, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (543, 'CJ5', 0, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (544, 'Commander', 157492, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (545, 'Grand Wagoneer', 0, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (546, 'Liberty', 188641, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (547, 'Asterion', 0, (SELECT id FROM brands WHERE brand_name = 'Lamborghini'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (548, 'Huracan', 0, (SELECT id FROM brands WHERE brand_name = 'Lamborghini'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (549, 'Veneno', 0, (SELECT id FROM brands WHERE brand_name = 'Lamborghini'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (550, 'Evoque', 690500, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (551, 'Freelander', 108600, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (552, 'LR3', 209962, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (553, 'LR4', 505630, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (554, 'Aviator', 0, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (555, 'LS', 97000, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (556, 'MKC', 499270, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (557, 'Town Car', 122750, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (558, 'Zephyr', 113700, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (559, 'CX7', 179026, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (560, 'Tribute', 0, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (561, 'MP4-12C', 0, (SELECT id FROM brands WHERE brand_name = 'McLaren'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (566, 'Clase CL', 937917, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (567, 'Clase CLK', 263046, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (568, 'Clase M', 578767, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (569, 'Clase R', 316430, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (570, 'Sprinter', 476619, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (571, 'Vito', 219848, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (572, 'Grand Marquis', 0, (SELECT id FROM brands WHERE brand_name = 'Mercury'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (573, 'Mariner', 0, (SELECT id FROM brands WHERE brand_name = 'Mercury'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (574, 'Milan', 0, (SELECT id FROM brands WHERE brand_name = 'Mercury'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (576, 'Mountaineer', 0, (SELECT id FROM brands WHERE brand_name = 'Mercury'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (578, 'CBO', 125775, (SELECT id FROM brands WHERE brand_name = 'Cbo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (580, 'Eclipse', 142225, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (581, 'Endeavor', 146240, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (582, 'Galant', 79163, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (583, 'Grandis', 125200, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (584, '240SX', 0, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (585, '350Z', 189600, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (586, 'Aprio', 69450, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (587, 'Cabstar', 294305, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (588, 'Estacas', 169790, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (589, 'NV2500', 303385, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (590, 'Platina', 58266, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (591, 'Quest', 128606, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (592, 'Tiida', 111954, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (593, 'Xterra', 0, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (595, '206', 63464, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (596, '307', 81807, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (597, '406', 0, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (598, '407', 93361, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (599, '607', 103000, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (600, 'Grand Raid', 89709, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (601, 'Partner', 172626, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (605, 'G-3', 70855, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (606, 'G-4', 66766, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (607, 'G-5', 88000, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (608, 'G-6', 95266, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (609, 'Grand Am', 0, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (610, 'Grand Prix', 0, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (611, 'Matiz', 44885, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (612, 'Montana', 107887, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (613, 'Solstice', 144780, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (614, 'Sunfire', 0, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (615, 'Torrent', 111772, (SELECT id FROM brands WHERE brand_name = 'Pontiac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (621, '918 Spyder', 0, (SELECT id FROM brands WHERE brand_name = 'Porsche'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (624, 'Clio', 108000, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (625, 'Euroclio', 0, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (627, 'Laguna', 66600, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (628, 'Megane', 80572, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (630, 'Scala', 94237, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (631, 'Scenic', 73400, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (632, 'Trafic Panel', 171911, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (633, 'Wraith', 0, (SELECT id FROM brands WHERE brand_name = 'Rolls Royce'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (634, '9-2', 0, (SELECT id FROM brands WHERE brand_name = 'Saab'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (635, '9-3', 0, (SELECT id FROM brands WHERE brand_name = 'Saab'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (636, '90', 0, (SELECT id FROM brands WHERE brand_name = 'Saab'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (639, 'Alhambra', 101700, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (640, 'Cordoba', 82635, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (641, 'Exeo', 211150, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (642, 'Forfour', 219000, (SELECT id FROM brands WHERE brand_name = 'Smart'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (643, 'B9 Tribeca', 0, (SELECT id FROM brands WHERE brand_name = 'Subaru'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (644, 'Tribeca', 235850, (SELECT id FROM brands WHERE brand_name = 'Subaru'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (645, 'Aerio', 62600, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (646, 'SX4', 134540, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (647, 'Vitara', 289756, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (648, 'XL7', 137360, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (649, '4Runner', 155264, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (650, 'Matrix', 109200, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (651, 'Rush', 113750, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (652, 'Solara', 113700, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (653, 'Tercel', 0, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (654, 'Yaris', 143268, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (655, 'Bora', 124253, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (656, 'Derby', 63075, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (657, 'Cabrio', 0, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (658, 'Caribe', 0, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (659, 'Golf', 252992, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (665, 'TLX', 478290, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (666, 'Spider', 0, (SELECT id FROM brands WHERE brand_name = 'Alfa Romeo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (667, 'Mirage', 167900, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (668, 'C30', 171037, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (672, 'DBS', 0, (SELECT id FROM brands WHERE brand_name = 'Aston Martin'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (673, 'DB9', 3859500, (SELECT id FROM brands WHERE brand_name = 'Aston Martin'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (674, 'Lagonda', 0, (SELECT id FROM brands WHERE brand_name = 'Aston Martin'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (675, 'Vantage', 2720250, (SELECT id FROM brands WHERE brand_name = 'Aston Martin'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (676, 'Vanquish', 5580000, (SELECT id FROM brands WHERE brand_name = 'Aston Martin'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (677, 'Rapide', 3906000, (SELECT id FROM brands WHERE brand_name = 'Aston Martin'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (678, 'Elise', 0, (SELECT id FROM brands WHERE brand_name = 'Lotus'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (679, 'Exige', 0, (SELECT id FROM brands WHERE brand_name = 'Lotus'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (680, 'Evora', 0, (SELECT id FROM brands WHERE brand_name = 'Lotus'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (681, 'MG3', 0, (SELECT id FROM brands WHERE brand_name = 'MG'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (682, 'MG6', 0, (SELECT id FROM brands WHERE brand_name = 'MG'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (683, 'S', 2137587, (SELECT id FROM brands WHERE brand_name = 'Tesla'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (684, 'X', 2326825, (SELECT id FROM brands WHERE brand_name = 'Tesla'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (685, '500', 0, (SELECT id FROM brands WHERE brand_name = 'Abarth'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (686, 'Forte', 270506, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (687, 'Sorento', 440080, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (688, 'Sportage', 368219, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (689, 'Logan', 174524, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (692, 'Macan', 1010744, (SELECT id FROM brands WHERE brand_name = 'Porsche'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (693, 'Escalade', 689650, (SELECT id FROM brands WHERE brand_name = 'Cadillac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (694, 'Silverado', 178660, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (695, 'Mini', 343512, (SELECT id FROM brands WHERE brand_name = 'Mini Cooper'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (696, 'Mini S', 323112, (SELECT id FROM brands WHERE brand_name = 'Mini Cooper'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (697, 'Coupe', 301593, (SELECT id FROM brands WHERE brand_name = 'Mini Cooper'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (698, 'Convertible', 290934, (SELECT id FROM brands WHERE brand_name = 'Mini Cooper'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (699, 'Roadster', 313133, (SELECT id FROM brands WHERE brand_name = 'Mini Cooper'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (700, 'Countryman', 331884, (SELECT id FROM brands WHERE brand_name = 'Mini Cooper'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (701, 'Paceman', 349017, (SELECT id FROM brands WHERE brand_name = 'Mini Cooper'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (702, 'John Cooper Works', 0, (SELECT id FROM brands WHERE brand_name = 'Mini Cooper'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (703, '207', 109263, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (704, '2008', 286114, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (705, 'V50', 126000, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (706, 'C70', 304557, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (707, 'S40', 149377, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (708, '488', 0, (SELECT id FROM brands WHERE brand_name = 'Ferrari'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (709, 'Tucson', 343817, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (710, 'CX5', 321758, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (711, 'HR-V', 311173, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (712, 'CX3', 295390, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (713, 'Clase GLA', 485557, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (714, 'Clase GLC', 723551, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (715, 'Clase GLE', 1368918, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (716, 'AMG GT', 2718345, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (717, 'Aero', 0, (SELECT id FROM brands WHERE brand_name = 'Saab'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (718, 'Ciaz', 216360, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (719, 'Clase V', 844904, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (722, 'Up', 163962, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (723, 'Optima', 360900, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (724, 'Rio', 223032, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (725, 'Leaf', 531990, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (726, 'S3', 0, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (727, '3', 0, (SELECT id FROM brands WHERE brand_name = 'Tesla'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (728, 'Twizy', 0, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (729, 'Soul', 275188, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (730, 'Volt', 658880, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (731, 'Figo', 171262, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (732, 'D20', 169088, (SELECT id FROM brands WHERE brand_name = 'Baic'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (733, 'X25', 237345, (SELECT id FROM brands WHERE brand_name = 'Baic'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (734, 'Ignis', 197956, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (735, 'Creta', 189895, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (737, 'SEI2', 383714, (SELECT id FROM brands WHERE brand_name = 'JAC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (738, 'SEI3', 346922, (SELECT id FROM brands WHERE brand_name = 'JAC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (802, 'Serie 500', 1142796, (SELECT id FROM brands WHERE brand_name = 'HINO'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1264, 'NSX', 3818225, (SELECT id FROM brands WHERE brand_name = 'Acura'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1265, 'Q2', 541153, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1266, 'BJ40', 520166, (SELECT id FROM brands WHERE brand_name = 'Baic'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1267, 'Bentayga', 4278000, (SELECT id FROM brands WHERE brand_name = 'Bentley'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1268, 'Serie Z', 555130, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1269, 'Envision', 597200, (SELECT id FROM brands WHERE brand_name = 'Buick'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1270, 'XT5', 775655, (SELECT id FROM brands WHERE brand_name = 'Cadillac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1271, 'CBO', 173000, (SELECT id FROM brands WHERE brand_name = 'Cbo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1272, 'Transit Van', 498596, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1273, 'Beat', 167757, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1274, 'Bolt EV', 695333, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1275, 'Cargo Van', 361027, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1276, 'Cavalier', 272971, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1277, 'Express Cutaway', 326457, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1278, 'Express Van', 439228, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1279, 'S-10', 270122, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1280, 'Sierra', 580652, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1281, 'Silverado 1500', 363866, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1282, 'Silverado 2500', 404665, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1283, 'Silverado 3500', 402850, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1284, 'ACCENT', 240760, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1285, 'SANTA FE', 533277, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1286, 'QX30', 632983, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1287, 'CITYSTAR', 717030, (SELECT id FROM brands WHERE brand_name = 'International'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1288, 'F Pace', 1300675, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1289, 'XE', 970270, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1290, 'NIRO', 452475, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1291, 'Discovery Sport', 772785, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1292, 'Range Rover Sport', 1326131, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1293, 'Continental', 1196750, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1294, 'Ghibli', 1320600, (SELECT id FROM brands WHERE brand_name = 'Maserati'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1295, 'Cargo Van', 504323, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1296, 'Chasis Cabina', 367440, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1297, 'Clase GLS', 1801912, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1298, 'Clase SLC', 835650, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1299, 'Clase SLS', 3415950, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1300, 'Crew Cab', 429587, (SELECT id FROM brands WHERE brand_name = 'Mercedes Benz'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1301, 'Chasis Cabina', 185095, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1302, 'Doble Cabina', 223808, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1303, 'Frontier', 347004, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1304, 'GT-R', 2180600, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1305, 'Kicks', 311277, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1306, 'Pick Up', 214570, (SELECT id FROM brands WHERE brand_name = 'Nissan'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1307, 'Partner Maxi', 221392, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1308, 'Captur', 307844, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1309, 'Kangoo Express', 175550, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1310, 'Twitzy Z.E.', 250300, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1311, 'ATECA', 406112, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1312, 'BRZ', 470283, (SELECT id FROM brands WHERE brand_name = 'Subaru'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1313, 'Hunter', 542000, (SELECT id FROM brands WHERE brand_name = 'UAZ'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1314, 'Caddy', 237534, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1315, 'Crafter', 426691, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1316, 'Crafter Pasajeros', 549187, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1317, 'Cross Golf', 277150, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1318, 'Jetta Nuevo', 214175, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1319, 'Transporter', 332755, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1320, 'S90', 1042940, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1321, 'Ducato Van', 285908, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1322, 'Mobi', 165188, (SELECT id FROM brands WHERE brand_name = 'Fiat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1523, 'Stinger', 647283, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1524, 'Ioniq', 438900, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1525, 'C-HR', 367400, (SELECT id FROM brands WHERE brand_name = 'Toyota'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1526, 'Renegade', 396920, (SELECT id FROM brands WHERE brand_name = 'Jeep'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1527, 'Starex', 416400, (SELECT id FROM brands WHERE brand_name = 'Hyundai'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1528, 'Sedona', 654650, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1536, 'Arona', 345150, (SELECT id FROM brands WHERE brand_name = 'Seat'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1537, 'Ram 1500', 453421, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1538, 'Ram 2500', 439179, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1539, 'Ram 4000', 379308, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1540, 'H 100 Wagon', 223850, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1541, 'Econoline Wagon', 291950, (SELECT id FROM brands WHERE brand_name = 'Ford'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1542, 'ELF 200', 380933, (SELECT id FROM brands WHERE brand_name = 'Isuzu'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1543, 'ELF 400', 481755, (SELECT id FROM brands WHERE brand_name = 'Isuzu'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1544, 'ELF 300', 426500, (SELECT id FROM brands WHERE brand_name = 'Isuzu'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1545, 'Clubman', 361742, (SELECT id FROM brands WHERE brand_name = 'Mini Cooper'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1546, 'GTS', 151950, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1547, 'Ram Promaster', 389350, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1548, 'Cabrio', 212563, (SELECT id FROM brands WHERE brand_name = 'Smart'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1549, 'Coupé', 181446, (SELECT id FROM brands WHERE brand_name = 'Smart'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1550, 'Vision', 156660, (SELECT id FROM brands WHERE brand_name = 'Dodge'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1551, 'Ram 700', 220046, (SELECT id FROM brands WHERE brand_name = 'RAM'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1552, 'ELF 100', 299800, (SELECT id FROM brands WHERE brand_name = 'Isuzu'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1553, 'GF60', 152850, (SELECT id FROM brands WHERE brand_name = 'FAW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1554, 'Giulia', 1187400, (SELECT id FROM brands WHERE brand_name = 'Alfa Romeo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1555, 'X65', 343880, (SELECT id FROM brands WHERE brand_name = 'Baic'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1556, 'Expert', 403700, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1557, 'Expert Van', 469750, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1558, 'Traveller', 682200, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1559, 'XC40', 684950, (SELECT id FROM brands WHERE brand_name = 'Volvo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1560, 'Stelvio', 1456666, (SELECT id FROM brands WHERE brand_name = 'Alfa Romeo'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1561, 'Q8', 1449900, (SELECT id FROM brands WHERE brand_name = 'Audi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1562, 'X35', 288900, (SELECT id FROM brands WHERE brand_name = 'Baic'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1563, 'X2', 652400, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1564, 'X7', 1769900, (SELECT id FROM brands WHERE brand_name = 'BMW'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1565, 'XT4', 746500, (SELECT id FROM brands WHERE brand_name = 'Cadillac'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1566, 'Serie 300', 811452, (SELECT id FROM brands WHERE brand_name = 'HINO'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1567, 'BRV', 333900, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1568, 'Insight', 549900, (SELECT id FROM brands WHERE brand_name = 'Honda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1569, 'QX50', 821233, (SELECT id FROM brands WHERE brand_name = 'Infiniti'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1570, 'Frison', 364000, (SELECT id FROM brands WHERE brand_name = 'JAC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1571, 'J4', 214000, (SELECT id FROM brands WHERE brand_name = 'JAC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1572, 'SEI7', 506500, (SELECT id FROM brands WHERE brand_name = 'JAC'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1573, 'E Pace', 1111564, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1574, 'I Pace', 2250375, (SELECT id FROM brands WHERE brand_name = 'Jaguar'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1575, 'Velar', 1252681, (SELECT id FROM brands WHERE brand_name = 'Land Rover'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1576, 'Nautilus', 951600, (SELECT id FROM brands WHERE brand_name = 'Lincoln'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1577, 'Eclipse Cross', 429950, (SELECT id FROM brands WHERE brand_name = 'Mitsubishi'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1578, '5008', 661566, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1579, 'Rifter', 339900, (SELECT id FROM brands WHERE brand_name = 'Peugeot'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1580, 'Oroch', 310900, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1581, 'Ertiga', 288323, (SELECT id FROM brands WHERE brand_name = 'Suzuki'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1582, 'Teramont', 788398, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1583, 'Kwid', 181566, (SELECT id FROM brands WHERE brand_name = 'Renault'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1734, 'Virtus', 321600, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1735, 'MX2', 0, (SELECT id FROM brands WHERE brand_name = 'Zacua'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1736, 'MX3', 0, (SELECT id FROM brands WHERE brand_name = 'Zacua'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1737, 'CX30', 439900, (SELECT id FROM brands WHERE brand_name = 'Mazda'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1738, 'Seltos', 0, (SELECT id FROM brands WHERE brand_name = 'KIA'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1739, 'Onix', 270500, (SELECT id FROM brands WHERE brand_name = 'Chevrolet'));
INSERT INTO models (id, name, average_price, brand_id) VALUES (1740, 'T-Cross', 0, (SELECT id FROM brands WHERE brand_name = 'Volkswagen'));